name: Build-Backend

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_URL: ${{ secrets.DB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Zip all files in lib/
        run: |
          cd build/libs/
          zip -r ../output.zip .
        if: success()

      - name: Upload lib ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-jar-output
          path: lib-jar-output.zip
