name: Teste Auto Scaling

# dispara manualmente ou a cada push em main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    # usa o ScaleSet Name que você definiu no chart
    runs-on: arc-runner-set

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verifica runner
        run: |
          echo "Estou rodando no runner autoescalável: ${{ runner.name }}"
          echo "Labels do runner: ${{ toJson(runner.labels) }}"

      - name: Teste simples
        run: |
          echo "✅ Runner autoescalável funcionando!"
